// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvsf5dPMiYGuscu8sQ-ckPiPf0XKvfie8',
    appId: '1:441641028868:web:eebb7db01b6d87e8f21451',
    messagingSenderId: '441641028868',
    projectId: 'flutter-2708c',
    authDomain: 'flutter-2708c.firebaseapp.com',
    storageBucket: 'flutter-2708c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBftxojcNDpshStbiUEOqr6ymkSkNw29iY',
    appId: '1:441641028868:android:f79d8a203638461ff21451',
    messagingSenderId: '441641028868',
    projectId: 'flutter-2708c',
    storageBucket: 'flutter-2708c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN4fflT8NOx-RMBZmOkPEsOwaBLFIbEMs',
    appId: '1:441641028868:ios:aa06f78f0bb636c3f21451',
    messagingSenderId: '441641028868',
    projectId: 'flutter-2708c',
    storageBucket: 'flutter-2708c.firebasestorage.app',
    iosBundleId: 'com.example.adminDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN4fflT8NOx-RMBZmOkPEsOwaBLFIbEMs',
    appId: '1:441641028868:ios:aa06f78f0bb636c3f21451',
    messagingSenderId: '441641028868',
    projectId: 'flutter-2708c',
    storageBucket: 'flutter-2708c.firebasestorage.app',
    iosBundleId: 'com.example.adminDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvsf5dPMiYGuscu8sQ-ckPiPf0XKvfie8',
    appId: '1:441641028868:web:e24bcd5568ec6c02f21451',
    messagingSenderId: '441641028868',
    projectId: 'flutter-2708c',
    authDomain: 'flutter-2708c.firebaseapp.com',
    storageBucket: 'flutter-2708c.firebasestorage.app',
  );
}
